LexiconLMS/Controllers/ActivityTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;

namespace LexiconLMS.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class ActivityTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ActivityTypes
        public ActionResult Index()
        {
            return View(db.ActivityTypes.ToList());
        }

        // GET: ActivityTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            return View(activityType);
        }

        // GET: ActivityTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ActivityTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] ActivityType activityType, string save1, string saveMultiple)
        {
            var existingType = db.ActivityTypes.AsNoTracking().Where(a => a.Name == activityType.Name).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (existingType == null)
                {
                    db.ActivityTypes.Add(activityType);
                    db.SaveChanges();
                    TempData["Event"] = "Activity Type " + activityType.Name + " added.";
                    if (save1 != null) return RedirectToAction("Index");
                    if (saveMultiple != null) return RedirectToAction("Create");
                    return RedirectToAction("Index"); //this redirect is unreachable since the if's above handle that
                }
                ModelState.AddModelError("Name", "An Activity Type with the same name already exists!");
            }

            return View(activityType);
        }

        // GET: ActivityTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            return View(activityType);
        }

        // POST: ActivityTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] ActivityType activityType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activityType).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Event"] = "Activity Type " + activityType.Name + " edited.";
                return RedirectToAction("Index");
            }
            return View(activityType);
        }

        // GET: ActivityTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            if (activityType.activities.Count == 0)
            {
                return View(activityType);
            }
            TempData["NegativeEvent"] = "You cannot remove Activity Type " + activityType.Name + " since it is in use.";
            return RedirectToAction("Index");
        }

        // POST: ActivityTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ActivityType activityType = db.ActivityTypes.Find(id);
            db.ActivityTypes.Remove(activityType);
            db.SaveChanges();
            TempData["Event"] = "Activity Type " + activityType.Name + " removed.";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LexiconLMS/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;

namespace LexiconLMS.Controllers
{
    public class FilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public bool DeleteFiles(ICollection<File> files)
        {
            bool result = true;
            if (files.Count > 0)
            {

                foreach (var f in files.ToList())
                {

                    try
                    {
                        File file = db.Files.Find(f.Id);
                        db.Files.Remove(file);
                        db.SaveChanges();
                        result = true;

                    }
                    catch (Exception)
                    {
                        return false;
                    }
                }
            }

            return result;


        }
        // GET: Files
        public ActionResult Index()
        {
            var files = db.Files.Include(f => f.User);
            return View(files.ToList());
        }

        // GET: Files/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // GET: Files/Create
        //public ActionResult Create()
        //{
        //    //ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "FirstName");
        //    return View();
        //}

        public ActionResult ShowCourseFiles(int courseId)
        {
            List<File> filesToShow = new List<File>();

            foreach (var file in db.Files)
            {
                if (file.CourseId==courseId)
                {
                    filesToShow.Add(file);
                }
            }
            
            return PartialView("_courseFiles",filesToShow);
        }

        public ActionResult ShowModuleFiles(int moduleId)
        {
            List<File> filesToShow = new List<File>();

            foreach (var file in db.Files)
            {
                if (file.ModuleId == moduleId)
                {
                    filesToShow.Add(file);
                }
            }

            return PartialView("_moduleFiles", filesToShow); 
        }


        // Ny post Create av Johan - under test
        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase upload, int activityId, string description)
         {
            if (upload != null && upload.ContentLength > 0)
            {
                if (User.IsInRole("Teacher"))
                {

                
                var document = new File
                {
                    FileName = System.IO.Path.GetFileName(upload.FileName),
                    //FileType = FileType.Document,
                    ContentType = upload.ContentType,
                    ActivityId = activityId
                };
                using (var reader = new System.IO.BinaryReader(upload.InputStream))
                {
                    document.Content = reader.ReadBytes(upload.ContentLength);
                }
                var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                if (user == null)
                {
                    return HttpNotFound();
                }
                document.UserId = user.Id;
                document.Description = description;
                // För tillfället bara lärare som laddar upp dokument -> PubliclyVisible = true
                // XXX Behöver ändras om Elever ska kunna ladda upp dokument
                document.PubliclyVisible = true;
                try
                {
                    db.Files.Add(document);
                    db.SaveChanges();
                    TempData["Event"] = "File " + document.FileName + " is uploaded.";
                }
                catch (Exception e)
                {
                    TempData["NegativeEvent"] = e.Message;
                }

                    //return RedirectToAction("Details", "Activities", new { id = activityId });

                } //end user is in role teacher

                if (User.IsInRole("Student"))
            {
                var document = new File
                {
                    FileName = System.IO.Path.GetFileName(upload.FileName),
                    //FileType = FileType.Document,
                    ContentType = upload.ContentType,
                    ActivityId = activityId
                };
                using (var reader = new System.IO.BinaryReader(upload.InputStream))
                {
                    document.Content = reader.ReadBytes(upload.ContentLength);
                }
                var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                if (user == null)
                {
                    return HttpNotFound();
                }
                document.UserId = user.Id;
                document.Description = description;
                    // För tillfället bara lärare som laddar upp dokument -> PubliclyVisible = true
                    // XXX Behöver ändras om Elever ska kunna ladda upp dokument
                    document.PubliclyVisible = false;
                try
                {
                    db.Files.Add(document);
                    db.SaveChanges();
                    TempData["Event"] = "File " + document.FileName + " is uploaded.";
                }
                catch (Exception e)
                {
                    TempData["NegativeEvent"] = e.Message;
                }
            } //end user is in role student

           
                }
            return RedirectToAction("Details", "Activities", new { id = activityId });
        }


        // Ny post Create av Johan - för filer på course nivå
        //denna är en modifiering av create på aktivitetsnivå pga av tidsnöd
        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCourseFile(HttpPostedFileBase upload, int courseId, string description)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                if (User.IsInRole("Teacher"))
                {
                    var document = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        //FileType = FileType.Document,
                        ContentType = upload.ContentType,
                        CourseId = courseId
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        document.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                    if (user == null)
                    {
                        return HttpNotFound();
                    }
                    document.UserId = user.Id;
                    document.Description = description;
                    // För tillfället bara lärare som laddar upp dokument -> PubliclyVisible = true
                    // XXX Behöver ändras om Elever ska kunna ladda upp dokument
                    document.PubliclyVisible = true;
                    try
                    {
                        db.Files.Add(document);
                        db.SaveChanges();
                        TempData["Event"] = "File " + document.FileName + " is uploaded.";
                    }
                    catch (Exception e)
                    {
                        TempData["NegativeEvent"] = e.Message;
                    }

                    //return RedirectToAction("Details", "Activities", new { id = activityId });

                } //end user is in role teacher
                
            }
            return RedirectToAction("Details", "Courses", new { id = courseId });
        }

        // Ny post Create av Johan - för filer på module nivå
        //denna är en modifiering av create på aktivitetsnivå pga av tidsnöd
        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateModuleFile(HttpPostedFileBase upload, int moduleId, string description)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                if (User.IsInRole("Teacher"))
                {
                    var document = new File
                   {
                       FileName = System.IO.Path.GetFileName(upload.FileName),
                       //FileType = FileType.Document,
                       ContentType = upload.ContentType,
                       ModuleId = moduleId
                   };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        document.Content = reader.ReadBytes(upload.ContentLength);
                    }

LexiconLMS/Views/Shared/_FileList.cshtml
@model IEnumerable<LexiconLMS.Models.File>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<hr />
<br />

<h3>@ViewBag.Heading</h3>

@if (Model.Count() > 0)
{
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            <thead>
                <tr>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => model.FileName)
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => model.UserId)
                    </th>
                    <!--
                    <th>
                        @Html.DisplayNameFor(model => model.ContentType)
                    </th>
                        -->
                    <th data-defaultsort='disabled'></th>
                </tr>
            </thead>


            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.FullName)
                    </td>
                    <!--
                    <td>
                        @Html.DisplayFor(modelItem => item.ContentType)
                    </td>
                    -->
                    <td>

                        @Html.ActionLink("Download", "Download", "Activities", new { id = item.Id }, new { target = "_blank" })
                        @if (User.IsInRole("Teacher") || item.User.Email == User.Identity.Name)
                        {
                            <span> | </span>
                            @Html.ActionLink("Delete", "Delete", "Files", new { id = item.Id }, null)
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
} else
{
    <p>There are no uploaded files.</p>
}

LexiconLMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lexicon LMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (User.IsInRole("Teacher"))
                {

                    <a href='@Url.Action("Index","Courses")'>
                        <img src='@Url.Content("~/Images/logo-lexicon.png")' alt="Lexicon">
                    </a>
                    @*@Html.ActionLink("Lexicon LMS", "Index", "Courses", new { area = "" }, new { @class = "navbar-brand" })*@
                @*@Html.ActionLink(" ", "Index", "Courses",null, new { @style = "background:url('~/Images/logo-lexicon_small.gif') no-repeat center right; display:block; height: 30px; width: 50px" })*@
                    //Html.ActionLink(" ", "Edit", new { id = c.ID }, new { @style = "background:url('../../Images/Menu/edit.png') no-repeat center right; display:block; height: 30px; width: 50px" }
                }
                else
                {
                    <a href='@Url.Action("StudentHome","Courses")'>
                        <img src='@Url.Content("~/Images/logo-lexicon.png")' alt="Lexicon" @*id="LexiconSmall"*@>
                    </a>
                        @*@Html.ActionLink("Lexicon LMS", "StudentHome", "Courses", new { area = "" }, new { @class = "navbar-brand" })*@
                        }

</div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Student"))
                    {
                        <li>@Html.ActionLink("Student List", "StudentList", "Account")</li>
                         
                    }
                    @if (User.IsInRole("Teacher"))
                    {
                        <li>@Html.ActionLink("Course List", "Index", "Courses")</li>
                       <li>@Html.ActionLink("Teacher List", "TeacherList", "Account")</li>
                        <li>@Html.ActionLink("Student List", "StudentList", "Account")</li>
                        <li>@Html.ActionLink("Activity Types", "Index", "ActivityTypes")</li> <!--TODO Flytta denna till ngn sub-meny?! -->
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lexicon</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LexiconLMS/Views/Shared/_StudentList.cshtml
@model IEnumerable<LexiconLMS.Models.UserViewModels>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
@if (User.IsInRole("Teacher"))
{
    <hr>

    <h3>Students</h3>
    @*if (TempData["Event"] != null)
    {
        <div class="Event alert alert-success" id="Event">
            <h4>
                @TempData["Event"]
            </h4>
        </div>
        <script type="text/javascript">
    $('#Event').delay(4000).hide(1500);
        </script>
    }*@
    if (TempData["NegativeEvent"] != null)
    {
        <div class="TempData alert alert-danger" id="Full">
            <h4>
                @TempData["NegativeEvent"]
            </h4>
        </div>
    }
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            <thead>
                <tr>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => model.Adress)
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th data-defaultsort='disabled'></th>
                </tr>
            </thead>
            @foreach (var item in Model.OrderBy(s => s.FirstName))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", "Account", new { email = item.Email }, null) |
                        @*@Html.ActionLink("Details", "Details", new { id = item.Email }, new { @style = "color:red;" }) |*@
                        @Html.ActionLink("Remove", "Delete", "Account", new { email = item.Email }, null)

                    </td>
                </tr>
            }

        </table>
        </div>
        } @*end if user is in role teacher*@

LexiconLMS/Views/Shared/_UpComingEvents.cshtml
@model IEnumerable<LexiconLMS.Models.Module>
@{int nrOfActivites = 0;
    var hrefName = "";
    var id = "";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script language="javascript">
        function toggle(elementId) {
            var ele = document.getElementById(elementId);
            if (ele.style.display == "block") {
                ele.style.display = "none";
            }
            else {
                ele.style.display = "block";
            }
        }
    </script>
</head>



@foreach (var item in Model)
{
    hrefName = "#collapse" + nrOfActivites + 1;
    id = "collapse" + nrOfActivites + 1;

    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href=@hrefName>
                        <b><i> @Html.DisplayFor(modelItem => item.Name) : </i></b>

                        <b>   @Html.DisplayFor(modelItem => item.Description)</b>
                    </a>
                </h4>
                <div class="model-details"> @Html.ActionLink("Details", "Details", "Modules", new { id = item.Id, courseName = @ViewBag.CourseName }, null) </div>
            </div>
        </div>
        <div id=@id class="panel-collapse collapse">
            <div class="panel-body">

                <b> @Html.Raw("Files on module level: ")</b> @item.Files.Count()
                <br />
                <br />

                @foreach (var activity in item.Activities.OrderBy(o => o.StartDateTime))
                {
                    @Html.DisplayFor(activityItem => activity.StartDateTime)
                    @Html.Raw(" to ")
                    @Html.DisplayFor(activityItem => activity.EndDateTime)
                    <br />
                    @Html.DisplayFor(activityItem => activity.Type.Name)
                    <br />
                    @Html.DisplayFor(activityItem => activity.Name)
                    <br />
                        var countPublicFiles = activity.Files.Where(f => f.PubliclyVisible == true).Count();
                        if (countPublicFiles > 0)
                        {
                    <b> @Html.Raw("Files: ")</b> @countPublicFiles
                    <br />
                        }

                        if (activity.StudentUpload && activity.IsOngoing(DateTime.Now))
                        {
                    <b style="color:red;">Assignment</b>
                    <br />
                        } else if (activity.StudentUpload)
                        {
                    <span style="color:orange;">Assignment</span>
                    <br />
                            }
                      
                    @Html.ActionLink("Details", "Details", "Activities", new { id = activity.Id, courseName = @ViewBag.CourseName }, null)  <br />
                    <br />
                }
            </div>
        </div>
        @*  slut på if nrofactivities==0*@
        @{nrOfActivites = nrOfActivites + 1;}
    </div>
}

LexiconLMS/Views/Shared/_courseFiles.cshtml
@model IEnumerable<LexiconLMS.Models.File>

@if (Model.Count() > 0)
{ <table class="table">
    <tr>
        <th>
            Uploader:
        </th>
        <th>            File name:        </th>
        <th>            @Html.DisplayNameFor(model => model.Description)        </th>
        <th></th>
    </tr>
@foreach (var item in Model) {
    <tr>
        <td>            @Html.DisplayFor(modelItem => item.User.FirstName) @Html.Raw(" ") @Html.DisplayFor(modelItem => item.User.LastName)</td>
        <td>            @Html.DisplayFor(modelItem => item.FileName)        </td>
        <td>            @Html.DisplayFor(modelItem => item.Description)        </td>
            @if (User.IsInRole("Teacher"))
            {
                <td>                    @Html.ActionLink("Delete", "DeleteCourseFile", "Files", new { id = item.Id}, null)</td>
            }
            @if (User.IsInRole("Student"))
            {
                <td>@Html.ActionLink("Download", "StudentDownloadFile", "Files", new { id = item.Id }, new { target = "_blank" })
                </td>
            }</tr>
}</table>
} @*end if model count is bigger than zero*@
         else   {<p>There are no uploaded files.</p>   }

LexiconLMS/Views/Shared/_moduleFiles.cshtml
@model IEnumerable<LexiconLMS.Models.File>

@if (Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                Uploader:
            </th>
            <th>
                File name:
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>

            @*<th>
                    @Html.DisplayNameFor(model => model.PubliclyVisible)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.CourseId)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.ActivityId)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.ContentType)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.Content)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.FileType)
                </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.FirstName) @Html.Raw(" ") @Html.DisplayFor(modelItem => item.User.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Path)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PubliclyVisible)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CourseId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActivityId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContentType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileType)
                    </td>*@

                @* @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |*@
                @if (User.IsInRole("Teacher"))
                {
                    <td>
                        @Html.ActionLink("Delete", "DeleteModuleFile", "Files", new { id = item.Id }, null)
                    </td>
                }
                @if (User.IsInRole("Student"))
                {
                    //denna bör funka men måste testas
                    <td>
                        @Html.ActionLink("Download", "StudentDownloadFile", "Files", new { id = item.Id }, new { target = "_blank" })
                    </td>
                }


            </tr>
        }

    </table>
} @*end if model count is bigger than zero*@

else
{<p>There are no uploaded files.</p>   }