LexiconLMS/Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LexiconLMS.Models
{
    public class Module
    {
        public int Id { get; set; }

        [Required]
        public int CourseId { get; set; }
        public virtual Course Course { get; }

        [Required]
        [Display(Name = "Module Name")]
        public string Name { get; set; }

        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true,
            DataFormatString = "{0:yyyy-MM-dd HH\\:mm}")]
        [Display(Name = "Start time")]
        public DateTime StartDateTime { get; set; }

        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true,
            DataFormatString = "{0:yyyy-MM-dd HH\\:mm}")]
        [Display(Name = "End time")]
        public DateTime EndDateTime { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public virtual ICollection<Activity> Activities { get; set; }

        public virtual ICollection<File> Files { get; set; }

        public bool IsOngoing(DateTime dateTime)
        {
            return StartDateTime <= dateTime && dateTime <= EndDateTime;
        }
    }
}

LexiconLMS/Controllers/ModulesController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;

namespace LexiconLMS.Controllers
{
    public class ModulesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Modules
        public ActionResult Index(int courseId)
        {
            ApplicationDbContext newDbContext = new ApplicationDbContext();
            // Find course name by courseId
            var course = newDbContext.Courses.First(u => u.Id == courseId);
            ViewBag.CourseName = course.Name;
            ViewBag.CourseId = courseId;
            return View(db.Modules.ToList().Where(c => c.CourseId == courseId));
        }

        // GET: Modules/Details/5
        public ActionResult Details(int? id, string courseName)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = db.Modules.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            if (courseName == null)
            {
                Course course = db.Courses.Find(module.CourseId);
                if (course == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                ViewBag.CourseId = course.Id;
                courseName = course.Name;
            }
            
            ViewBag.CourseName = courseName;
            
            return View(module);
        }

        // GET: Modules/Create
        [Authorize(Roles = "Teacher")]
        public ActionResult Create(int courseId, string courseName)
        {

            //gör denna cyklisk så att viewbag alltid är populerad även när man trycker på refresh hos klienten
           Course course= db.Courses.Find(courseId);

            ViewBag.CourseName = course.Name;
            ViewBag.CourseId = course.Id;
            return View();
        }

        // POST: Modules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Create(string Add, [Bind(Include = "Id,CourseId,Name,StartDateTime,EndDateTime,Description")] Module module)
        {
            if (ModelState.IsValid)
            {
                ViewBag.CourseId = module.CourseId;
                //ApplicationDbContext newDbContext = new ApplicationDbContext();
                // Find course name by courseId
                var course = db.Courses.First(u => u.Id == module.CourseId);
                if (course.StartDate > module.StartDateTime)
                {
                    ModelState.AddModelError("StartDateTime", "Start date can´t be earlier than course start date " + course.StartDate.ToString("yyyy-MM-dd HH:mm"));
                    //in med viewbags för modules
                    ViewBag.CourseName = course.Name;
                    ViewBag.CourseId = course.Id;
                    return View();
                }
                if (module.StartDateTime >= module.EndDateTime)
                {
                    ModelState.AddModelError("StartDateTime", "The End Time cannot be earlier than the Start Time " + module.StartDateTime.ToString("yyyy-MM-dd HH:mm"));
                    //in med viewbags för modules
                    ViewBag.CourseName = course.Name;
                    ViewBag.CourseId = course.Id;
                    return View();
                }
                //Find modules by CourseId
                var modules = db.Modules.ToList().Where(c => c.CourseId == module.CourseId);

                foreach (var mod in modules)
                {
                    if (module.StartDateTime == mod.StartDateTime)
                    {
                        ModelState.AddModelError("StartDateTime", "Start Time of the module overlaps with Start date for module '" + mod.Name + "' that starts " + mod.StartDateTime.ToString("yyyy-MM-dd HH:mm"));
                        //in med viewbags för modules
                        ViewBag.CourseName = course.Name;
                        ViewBag.CourseId = course.Id;
                        return View();
                    }
                    else if (module.StartDateTime < mod.StartDateTime)
                    {
                        if (module.EndDateTime > mod.StartDateTime)
                        {
                            ModelState.AddModelError("EndDateTime", "End Time overlaps Start Time for module '" + mod.Name + "' that starts " + mod.StartDateTime.ToString("yyyy-MM-dd HH:mm"));
                            //in med viewbags för modules
                            ViewBag.CourseName = course.Name;
                            ViewBag.CourseId = course.Id;
                            return View();
                        }
                    }
                    else if (module.StartDateTime > mod.StartDateTime)
                    {
                        if (module.StartDateTime < mod.EndDateTime)
                        {
                            ModelState.AddModelError("StartDateTime", "Start Time overlaps End Time for module '" + mod.Name + "' that ends '" + mod.EndDateTime.ToString("yyyy-MM-dd HH:mm"));
                            //in med viewbags för modules
                            ViewBag.CourseName = course.Name;
                            ViewBag.CourseId = course.Id;
                            return View();
                        }
                    }
                }
                try
                {
                db.Modules.Add(module);
                db.SaveChanges();
                TempData["Event"] = "Module " + module.Name + " added.";

                switch (Add)
                {
                    case "Save":
                        return RedirectToAction("Index", new { courseId = module.CourseId });
                    case "Save & add new module":
                        ModelState.Clear();
                            //in med viewbags för modules
                            ViewBag.CourseName = course.Name;
                            ViewBag.CourseId = course.Id;
                            return View();
                    default:
                        throw new Exception();
                        //break;
                }

            }
                catch (Exception e)
                {
                    TempData["NegativeEvent"] = e.Message;
                    return View();
                }
            }
            return View(module);
        }

        // GET: Modules/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id, string courseName)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = db.Modules.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseName = courseName;
            ViewBag.CourseId = module.CourseId;
            return View(module);
        }

        // POST: Modules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit([Bind(Include = "Id,CourseId,Name,StartDateTime,EndDateTime,Description")] Module module)
        {
            
            if (ModelState.IsValid)
            {
                var course = db.Courses.First(u => u.Id == module.CourseId);
                ViewBag.CourseId = course.Id;
                ViewBag.CourseName = course.Name;
                if (course.StartDate > module.StartDateTime)
                {
                    ModelState.AddModelError("StartDateTime", "Start date can´t be earlier than course start date " + course.StartDate.ToString("yyyy-MM-dd HH:mm"));
                    return View(module);
                }
                if (module.StartDateTime >= module.EndDateTime)
                {
                    ModelState.AddModelError("StartDateTime", "The End Time cannot be earlier than the Start Time " + module.StartDateTime.ToString("yyyy-MM-dd HH:mm"));
                    return View(module);
                }
                
                //Find modules by CourseId
                var modules = db.Modules.AsNoTracking().ToList().Where(c => c.CourseId == module.CourseId);
                //var activities = module.Activities.ToList();
                foreach (var mod in modules)
                {   
                    
                    if (module.Id == mod.Id)
                    {
                        foreach (var activity in mod.Activities)
                        {
                            if (module.StartDateTime > activity.StartDateTime)
                            {
                                TempData["NegativeEvent"] = "You can't save because you have an activity that starts earlier than the new module startdate";
                                return View(module);
                            }
                            else if (module.EndDateTime < activity.EndDateTime)
                            {
                                TempData["NegativeEvent"] = "You can't save because you have an activity that ends later than the new module enddate";
                                return View(module);
                            }
                        }
                    }
                }

LexiconLMS/Views/Modules/Create.cshtml
@model LexiconLMS.Models.Module

@{
    ViewBag.Title = "Create";
  
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Details","Courses",new {id=ViewBag.CourseId })'>@ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Modules",new {courseId=ViewBag.CourseId })'>Modules for @ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Create","Modules",new {courseId=ViewBag.CourseId })'>Add Module for @ViewBag.CourseName</a></li>
    </ol>
}
<h2>Add Module for Course @ViewBag.CourseName</h2>
@if (TempData["Event"] != null)
{
    <div class="Event alert alert-success" id="Event">
        <h4>
            @TempData["Event"]
        </h4>
    </div>
    <script type="text/javascript">
    $('#Event').delay(4000).hide(1500);
    </script>
}

@if (TempData["NegativeEvent"] != null)
{
    <div class="TempData alert alert-danger" id="Full">
        <h4>
            @TempData["NegativeEvent"]
        </h4>
    </div>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
   
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--<div class="form-group">
            @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>-->
        <input type="hidden" name="courseId" value= @ViewBag.CourseId />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD HH:mm" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control", placeholder = "YYYY-MM-DD HH:mm" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
         
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name ="Add" id ="Save" value="Save" class="btn btn-default" />
                <input type="submit" name="Add"  id ="SaveNew" value="Save & add new module" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { courseId = @ViewBag.CourseId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")



    


}

LexiconLMS/Views/Modules/Delete.cshtml
@model LexiconLMS.Models.Module

@{
    ViewBag.Title = "Remove";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Details","Courses",new {id=ViewBag.CourseId })'>@ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Modules",new {courseId=ViewBag.CourseId })'>Modules for @ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Delete","Modules",new {courseId=ViewBag.CourseId,courseName=ViewBag.CourseName })'>Delete Module @Model.Name</a></li>
    </ol>
}
<h2>Remove</h2>

<h3>Are you sure you want to remove this Module?</h3>
<div>
    <h4>Module for Course @ViewBag.CourseName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.HiddenFor(model => model.CourseId)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.CourseId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remove" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new {courseId = Model.CourseId })
        </div>
    }
</div>

LexiconLMS/Views/Modules/Details.cshtml
@model LexiconLMS.Models.Module
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
@{
    ViewBag.Title = "Module Details";
}
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Details","Courses",new {id=Model.CourseId })'>@ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Modules",new {courseId=Model.CourseId })'>Modules for @ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Details","Modules",new {courseId=ViewBag.CourseId })'>Activities for Module @Model.Name</a></li>
    </ol>
}

@if (User.IsInRole("Student"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("StudentHome","Courses")'>Course Home Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Modules",new { courseId = Model.CourseId })'>@ViewBag.courseName Student Modules Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Details", "Modules",new {id=Model.Id})'>Module @Html.Raw(Model.Name)</a></li>
    </ol>
}
<h2>Module @Html.Raw(Model.Name) in Course @ViewBag.courseName</h2>

<div>
    <dl class="dl-horizontal">

        <dd>
            @Html.HiddenFor(model => model.CourseId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
@if (User.IsInRole("Teacher"))
{
    <p>
        @Html.ActionLink("Add Activity", "Create", "Activities", new { moduleId = Model.Id }, null) |
        @Html.ActionLink("Edit Module Info", "Edit", new { id = Model.Id, courseName = ViewBag.CourseName }) |
        @Html.ActionLink("Module List", "Index", new { courseId = Model.CourseId })
    </p>
} else
{
    <p>
        @Html.ActionLink("Module List", "Index", new { courseId = Model.CourseId })
    </p>
}
<hr>
@*file upload area for course*@
@if (User.IsInRole("Teacher"))
{
    using (Html.BeginForm("CreateModuleFile", "Files", new { moduleId = Model.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
       
       
        <div class="row">
            <div class="col-md-5">
                <div class="form-group">
                    @Html.Label("File upload at Module level.")
                    <input type="file" name="upload" />
                    <br />
                    @*</div>*@
                    @*<div class="form-group" >*@
                    @Html.Label("Description:")
                    &nbsp;
                    <input class="form-control input-sm" name="description" />
                    @*</div>*@
                    @*<div class="form-group">*@
                    <input type="submit" value="Upload" class="btn btn-default" />
                </div>
            </div>@*end of upload area div*@
            <div class="col-md-7">
                <h4>Uploaded files at module level:</h4>
                @Html.Action("ShowModuleFiles", "Files", new { moduleId = Model.Id })
            </div>@*end of row already uploaded files*@

        </div> @*end of row div*@
    }
}@* end of @using html.beginform *@
 
@if (User.IsInRole("Student")) //visa list över moduldokument för studenter
{
    <div class="row">
        <div class="col-xs-12">
            <h3>Module Documents</h3>
            <p>
                <!-- Table of course documents-->
                @Html.Action("ShowModuleFiles", "Files", new { moduleId = Model.Id })
            </p>
            <br />
        </div>
    </div>
}



<hr>
<h3>Activities</h3>

@if (TempData["Event"] != null)
{
    <div class="Event alert alert-success" id="Event">
        <h4>
            @TempData["Event"]
        </h4>
    </div>
    <script type="text/javascript">
        $('#Event').delay(4000).hide(1500);
    </script>
}
@if (TempData["NegativeEvent"] != null)
{
    <div class="TempData alert alert-danger" id="Full">
        <h4>
            @TempData["NegativeEvent"]
        </h4>
    </div>
}

@if (Model.Activities.Count > 0)
{
    var firstItem = Model.Activities.First();
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            <thead>
                <tr>
                    <th data-defaultsign="AZ">
                        <!-- @Html.DisplayNameFor(model => firstItem.Type) -->
                        Type
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => firstItem.Name)
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => firstItem.StartDateTime)
                    </th>
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => firstItem.EndDateTime)
                    </th>
                    <th data-defaultsign="AZ">
                        Files
                    </th>
                    @if (User.IsInRole("Teacher"))
                {
                        <th data-defaultsign="AZ">
                            Student Files
                        </th>
                    }
                    <!--
                    <th data-defaultsign="AZ">
                        @Html.DisplayNameFor(model => firstItem.Description)
                    </th>
                        -->
                    <th data-defaultsort='disabled'></th>
                </tr>
            </thead>

            @foreach (var item in Model.Activities.OrderBy(a => a.StartDateTime))
            {

                <tr title="@item.Description">
                    <td>
                        @Html.DisplayFor(modelItem => item.Type.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDateTime)
                    </td>
                    @{var countPublicFiles = item.Files.Where(f => f.PubliclyVisible == true).Count();
                        <td>@countPublicFiles </td>
                    }
                    @if (User.IsInRole("Teacher"))
                    {
                        var countPrivateFiles = item.Files.Where(f => f.PubliclyVisible == false).Count();
                        <td>@countPrivateFiles </td>
                    }
                    @if (User.IsInRole("Teacher"))
                    {
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Activities", new { id = item.Id }, null) |
                            @Html.ActionLink("Details", "Details", "Activities", new { id = item.Id }, null) |
                            @Html.ActionLink("Remove", "Delete", "Activities", new { id = item.Id }, null)
                        </td>
                    }
                    @if (User.IsInRole("Student"))
                    {
                        <td>
                            @Html.ActionLink("Details", "Details", "Activities", new { id = item.Id }, null)
                        </td>
                    }
                </tr>
                        }

        </table>
        </div>
        } else {
        <p>No activities have been added so far.</p>
        }

LexiconLMS/Views/Modules/Edit.cshtml
@model LexiconLMS.Models.Module

@{
    ViewBag.Title = "Edit";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Details","Courses",new {id=ViewBag.CourseId })'>@ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Modules",new {courseId=ViewBag.CourseId })'>Modules for @ViewBag.CourseName</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Edit","Modules",new {courseId=ViewBag.CourseId,courseName=ViewBag.CourseName })'>Edit Module @Model.Name</a></li>
    </ol>
}
<h2>Edit</h2>
<br />
@if (TempData["Event"] != null)
{
    <div class="Event alert alert-success" id="Event">
        <h4>
            @TempData["Event"]
        </h4>
    </div>
    <script type="text/javascript">
    $('#Event').delay(4000).hide(1500);
    </script>
}

@if (TempData["NegativeEvent"] != null)
{
    <div class="TempData alert alert-danger" id="Full">
        <h4>
            @TempData["NegativeEvent"]
        </h4>
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Module for Course @ViewBag.CourseName</h4>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
           <!-- @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-10">
                @Html.HiddenFor(model => model.CourseId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Module List", "Index", new { courseId = Model.CourseId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}