LexiconLMS/Controllers/ActivityTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;

namespace LexiconLMS.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class ActivityTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ActivityTypes
        public ActionResult Index()
        {
            return View(db.ActivityTypes.ToList());
        }

        // GET: ActivityTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            return View(activityType);
        }

        // GET: ActivityTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ActivityTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] ActivityType activityType, string save1, string saveMultiple)
        {
            var existingType = db.ActivityTypes.AsNoTracking().Where(a => a.Name == activityType.Name).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (existingType == null)
                {
                    db.ActivityTypes.Add(activityType);
                    db.SaveChanges();
                    TempData["Event"] = "Activity Type " + activityType.Name + " added.";
                    if (save1 != null) return RedirectToAction("Index");
                    if (saveMultiple != null) return RedirectToAction("Create");
                    return RedirectToAction("Index"); //this redirect is unreachable since the if's above handle that
                }
                ModelState.AddModelError("Name", "An Activity Type with the same name already exists!");
            }

            return View(activityType);
        }

        // GET: ActivityTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            return View(activityType);
        }

        // POST: ActivityTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] ActivityType activityType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activityType).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Event"] = "Activity Type " + activityType.Name + " edited.";
                return RedirectToAction("Index");
            }
            return View(activityType);
        }

        // GET: ActivityTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActivityType activityType = db.ActivityTypes.Find(id);
            if (activityType == null)
            {
                return HttpNotFound();
            }
            if (activityType.activities.Count == 0)
            {
                return View(activityType);
            }
            TempData["NegativeEvent"] = "You cannot remove Activity Type " + activityType.Name + " since it is in use.";
            return RedirectToAction("Index");
        }

        // POST: ActivityTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ActivityType activityType = db.ActivityTypes.Find(id);
            db.ActivityTypes.Remove(activityType);
            db.SaveChanges();
            TempData["Event"] = "Activity Type " + activityType.Name + " removed.";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LexiconLMS/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;

namespace LexiconLMS.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        ////file handler written by Johan - it is not complete
        //[HttpPost]
        //public ActionResult Upload(string userName, int courseId, HttpPostedFileBase upload) //username is the Identity username(email) and Id is the course Id
        //{
        //    if (upload != null && upload.ContentLength > 0)
        //    {
        //        var file = new File
        //        {
        //            Path = System.IO.Path.GetFileName(upload.FileName),
        //            FileType = FileType.Document,
        //            ContentType = upload.ContentType,
        //            CourseId = courseId,


        //        };
        //        //using (var reader = new System.IO.BinaryReader(upload.InputStream))
        //        //{
        //        //    file.Content = reader.ReadBytes(upload.ContentLength);
        //        //}
        //        //student.Files = new List<File> { avatar };
        //    }


        //    return View();
        //}


        // GET: Courses
        public ActionResult Index()
        {
            if (User.IsInRole("Student"))
            {
                return RedirectToAction("StudentHome");
            }
            return View(db.Courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.IsInRole("Student"))
            {
                return RedirectToAction("StudentHome");
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/StudentHome
        public ActionResult StudentHome()
        {
            //ApplicationUserManager manager = new ApplicationUserManager()
            //var user = await UserManager.FindByNameAsync(User.Identity.Name);
            if (User.IsInRole("Student"))
            {
                var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                if (user != null)
                {
                    Course course = db.Courses.Find(user.CourseId);
                    if (course != null)
                    {
                        return View(course);
                    }
                    return HttpNotFound();
                }
                return HttpNotFound();
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Teacher")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        //modified parameter head to allow save multiple and redirect appropriately - test
        public ActionResult Create([Bind(Include = "Id,Name,StartDate,Description"),] Course course, string save1, string saveMultiple)
        {
            //kontroll av att startdatum inte är satt tidigare än idag
            if (course.StartDate < DateTime.Today)
            {
                //felmeddelande + returnera view
                //ViewBag.Message = "You tried to create a course with a startdate earlier than today. Please try again.";
                //använder tempdata istället
                TempData["CreateError"] = "You tried to create a course with a start date earlier than today. Please try again!";
                return View();
            }
            //kontroll av att kursnamnet är unikt
            foreach (var existingcourse in db.Courses)
            {
                if (existingcourse.Name == course.Name)
                {//kurs med det namnet existerar redan i databasen. skicka felmeddelande till klient.
                    TempData["CreateError"] = "You tried to create a course with a name that already exists. Please try again with another name!";
                    return View();
                }
            }
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                //meddelande till klient att kursen är skapad
                TempData["Event"] = "Course " + course.Name + " added.";
                //return RedirectToAction("Index");//, new { Id = course.Id });
            }

            //code for appropriate redirects below
            if (save1 != null) return RedirectToAction("Index");
            if (saveMultiple != null) return RedirectToAction("Create");
            return View(course);//should not be able to reach this return
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit([Bind(Include = "Id,Name,StartDate,Description")] Course course)
        {
            var oldCourse = db.Courses.AsNoTracking().FirstOrDefault(c => c.Id == course.Id);
            if (oldCourse == null)
            {
                return HttpNotFound();
            }
            var modules = oldCourse.Modules;
            if (ModelState.IsValid)
            {
                if (oldCourse.StartDate < course.StartDate &&
                    oldCourse.Modules.Count > 0 &&
                    modules.OrderBy(m => m.StartDateTime)
                    .First().StartDateTime < course.StartDate)
                {
                    ModelState.AddModelError("StartDate", "StartDate overlaps first module.");
                    return View(course);
                }
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                //text till klient
                TempData["Event"] = "Course " + course.Name + " edited.";
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteConfirmed(int id)
        {
            bool result = true;
            var file = new FilesController();
            Course course = db.Courses.AsNoTracking().FirstOrDefault(a => a.Id == id);   //Find(id);
            var modules = course.Modules.ToList();
            foreach (var m in modules)
            {
                var activities = m.Activities.ToList();
                foreach (var a in activities)
                {
                    var activityFiles = a.Files.ToList();
                    result = file.DeleteFiles(activityFiles);
                }
                if (result)
                {
                    var moduleFiles = m.Files.ToList();
                    result = file.DeleteFiles(moduleFiles);
                    if (!result)
                    {
                        TempData["NegativeEvent"] = "Course " + course.Name + " not removed.";
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    TempData["NegativeEvent"] = "Course " + course.Name + " not removed.";
                    return RedirectToAction("Index");
                }
            }
            if (result)
            {
                var courseFiles = course.Files.ToList();
                result = file.DeleteFiles(courseFiles);
                if (!result)
                {
                    TempData["NegativeEvent"] = "Course " + course.Name + " not removed.";
                    return RedirectToAction("Index");
                }
            }


            bool sucess = DeleteStudents(id);
            
            if (sucess)
            {
                course = db.Courses.Find(id);
                //Course course = db.Courses.Include(m => m.C(id);

                try
                {
                    db.Courses.Remove(course);
                    db.SaveChanges();
                    TempData["Event"] = "Course " + course.Name + " removed.";
                } catch (Exception e)
                {
                    TempData["NegativeEvent"] = e.Message;
                }
            }

LexiconLMS/Views/ActivityTypes/Create.cshtml
@model LexiconLMS.Models.ActivityType

@{
    ViewBag.Title = "Create Activity Type";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","ActivityTypes")'>Manage Activity Types</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Create","ActivityTypes")'>Create Activity Type</a></li>
    </ol>
}
<h2>Create Activity Type</h2>
@if (TempData["Event"] != null)
{
    <div class="Event alert alert-success" id="Event">
        <h4>
            @TempData["Event"]
        </h4>
    </div>
    <script type="text/javascript">
    $('#Event').delay(4000).hide(1500);
    </script>
}

@if (TempData["NegativeEvent"] != null)
{
    <div class="TempData alert alert-danger" id="Full">
        <h4>
            @TempData["NegativeEvent"]
        </h4>
    </div>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="save1" value="Save" class="btn btn-default" />
                <input type="submit" name="saveMultiple" value="Save & add new activity type" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Activity Type List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/Views/ActivityTypes/Delete.cshtml
@model LexiconLMS.Models.ActivityType
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
@{
    ViewBag.Title = "Delete Activity Type";
}
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","ActivityTypes")'>Manage Activity Types</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Delete","ActivityTypes",new { id = Model.Id })'>Remove Activity Type @Model.Name</a></li>
    </ol>
}
<h2>Remove Activity Type</h2>

<h3>Are you sure you want to remove this?</h3>
@if (TempData["Event"] != null)
{
    <div class="Event alert alert-success" id="Event">
        <h4>
            @TempData["Event"]
        </h4>
    </div>
    <script type="text/javascript">
    $('#Event').delay(4000).hide(1500);
    </script>
}

@if (TempData["NegativeEvent"] != null)
{
    <div class="TempData alert alert-danger" id="Full">
        <h4>
            @TempData["NegativeEvent"]
        </h4>
    </div>
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remove" class="btn btn-default" /> |
            @Html.ActionLink("Back to Activity Type List", "Index")
        </div>
    }
</div>

LexiconLMS/Views/ActivityTypes/Details.cshtml
@model LexiconLMS.Models.ActivityType

@{
    ViewBag.Title = "Details";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<h2>Details</h2>

<div>
    <h4>ActivityType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LexiconLMS/Views/ActivityTypes/Edit.cshtml
@model LexiconLMS.Models.ActivityType

@{
    ViewBag.Title = "Edit";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","ActivityTypes")'>Manage Activity Types</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Edit","ActivityTypes",new { id = Model.Id })'>Edit Activity Type @Model.Name</a></li>
    </ol>
}
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Activity Type</h4>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Activity Type List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/Views/ActivityTypes/Index.cshtml
@model IEnumerable<LexiconLMS.Models.ActivityType>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
@{
    ViewBag.Title = "Activity Types";
}
@if (User.IsInRole("Teacher"))
{
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","Courses")'>Courses Overview Page</a></li>
        <li class="breadcrumb-item active"><a href='@Url.Action("Index","ActivityTypes")'>Manage Activity Types</a></li>
    </ol>
}
<h2>Activity Types</h2>
@if (TempData["Event"] != null)
{
    <div class="Event alert alert-success" id="Event">
        <h4>
            @TempData["Event"]
        </h4>
    </div>
    <script type="text/javascript">
        $('#Event').delay(4000).hide(1500);
    </script>
}
@if (TempData["NegativeEvent"] != null)
{
    <div class="TempData alert alert-danger" id="Full">
        <h4>
            @TempData["NegativeEvent"]
        </h4>
    </div>
}

<p>
    @Html.ActionLink("Add ActivityType", "Create")
</p>
<div class="table-responsive">
    <table class="table table-bordered table-condensed table-striped table-hover sortable">
        <thead>
            <tr>
                <th data-defaultsign="AZ">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th data-defaultsort='disabled'></th>
            </tr>
        </thead>

        @foreach (var item in Model.OrderBy(a => a.Name))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    <!--            @Html.ActionLink("Details", "Details", new { id=item.Id }) | -->
                    @if (item.activities.Count == 0)
                {
                        <span>| </span> @Html.ActionLink("Remove", "Delete", new { id = item.Id })
                    }
                </td>
            </tr>
        }

    </table>
    </div>